
cc_test(
    name = "test_flat_filepath",
    srcs = ["test_flat.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@com_google_googletest//:gtest",
        "//:boost_file_test"
    ],
)
